document.addEventListener("DOMContentLoaded",()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const progress=$('.reading-progress'), fill=$('.sidebar-progress__fill'), sidebar=$('.sidebar');
function progressUpdate(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),v=Math.max(0,Math.min(1,scrollY/max));if(progress)progress.style.transform=`scaleX(${v})`;if(fill)fill.style.height=`${v*100}%`;}
const hero=$('.hero'), heroImg=$('.hero__image'), heroContent=$('.hero__content');
function heroUpdate(){if(!hero||!heroImg)return;const r=hero.getBoundingClientRect(),vh=innerHeight;if(r.bottom<=0||r.top>=vh)return;const p=Math.max(0,Math.min(1,-r.top/Math.max(1,r.height)));heroImg.style.transform=`translate3d(0,${p*42}px,0) scale(${1.045+p*.035})`;if(heroContent){heroContent.style.transform=`translate3d(0,calc(-50% + ${-p*24}px),0)`;heroContent.style.opacity=Math.max(0,1-p*1.2);}}
if(sidebar)sidebar.classList.add('is-visible');
$$('.sidebar__toggle').forEach(b=>{const g=b.closest('.sidebar__group');if(!g)return;g.classList.remove('is-expanded');b.setAttribute('aria-expanded','false');b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=g.classList.toggle('is-expanded');b.setAttribute('aria-expanded',String(open));});});
const links=$$('.sidebar__link').map(link=>{const id=link.getAttribute('href');const target=id&&id.startsWith('#')?document.getElementById(id.slice(1)):null;return target?{link,target}:null}).filter(Boolean);
function activeUpdate(){let cur=null,mark=scrollY+innerHeight*.3;for(const x of links){if(x.target.offsetTop<=mark)cur=x;else break;}links.forEach(x=>x.link.classList.remove('is-active'));if(cur)cur.link.classList.add('is-active');}
$$('.comparison').forEach(box=>{const after=$('.comparison__after',box),div=$('.comparison__divider',box),handle=$('.comparison__handle',box);if(!after||!div||!handle)return;let v=50;function set(x){const r=box.getBoundingClientRect();v=Math.max(0,Math.min(100,(x-r.left)/r.width*100));after.style.clipPath=`inset(0 0 0 ${v}%)`;div.style.left=handle.style.left=`${v}%`;handle.setAttribute('aria-valuenow',Math.round(v));}let drag=false;box.addEventListener('pointerdown',e=>{drag=true;box.setPointerCapture?.(e.pointerId);set(e.clientX)});box.addEventListener('pointermove',e=>{if(drag)set(e.clientX)});box.addEventListener('pointerup',()=>drag=false);box.addEventListener('pointercancel',()=>drag=false);handle.tabIndex=0;handle.setAttribute('role','slider');handle.setAttribute('aria-valuemin','0');handle.setAttribute('aria-valuemax','100');handle.setAttribute('aria-valuenow','50');handle.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();v+=e.key==='ArrowRight'?2:-2;const r=box.getBoundingClientRect();set(r.left+r.width*v/100);});});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const t=document.querySelector(id);if(!t)return;e.preventDefault();scrollTo({top:t.getBoundingClientRect().top+scrollY-28,behavior:'smooth'});}));
$$('[data-note-link]').forEach(a=>a.addEventListener('click',()=>{const id=a.getAttribute('href');setTimeout(()=>{const t=id&&document.querySelector(id);if(t){t.classList.add('note-highlight');setTimeout(()=>t.classList.remove('note-highlight'),1800)}},450)}));
if(hero)requestAnimationFrame(()=>hero.classList.add('is-loaded'));let ticking=false;function update(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{progressUpdate();heroUpdate();activeUpdate();ticking=false})}progressUpdate();heroUpdate();activeUpdate();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);
});